version: '2'
services:
  app:
    container_name: gc-app
    image: gc-app-image
    build:
      context: frontend/
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - "gc_node_modules:/app/node_modules"
      - "./frontend:/app"

volumes:
  gc_node_modules:
    name: gc_node_modules_volume